export const bstProblems = [
  { id: 16, title: 'Invert Binary Tree', difficulty: 'Easy', pattern: 'DFS', viz: 'bst',
    description: 'Given the root of a binary tree, invert (mirror) the tree and return its root.',
    examples: [{ input: 'root = [4,2,7,1,3,6,9]', output: '[4,7,2,9,6,3,1]', explanation: 'Left and right subtrees are swapped at every level.' }],
    hints: ['At each node you need to swap its left and right children.', 'After swapping, you need to invert both subtrees too.', 'DFS recursion: swap children, recurse left, recurse right. Base case: null node.'],
    pattern_explanation: 'DFS post-order or pre-order. Swap at every node recursively.',
    solution: `function invertTree(root) {\n  if (!root) return null;\n  [root.left, root.right] = [root.right, root.left];\n  invertTree(root.left);\n  invertTree(root.right);\n  return root;\n}`,
    testCases: [] },
  { id: 17, title: 'Maximum Depth of Binary Tree', difficulty: 'Easy', pattern: 'DFS', viz: 'bst',
    description: 'Given the root of a binary tree return its maximum depth (number of nodes along the longest path from root to leaf).',
    examples: [{ input: 'root = [3,9,20,null,null,15,7]', output: '3', explanation: 'Longest path: 3→20→15 or 3→20→7.' }],
    hints: ['Depth of a tree = 1 + max(depth of left subtree, depth of right subtree).', 'Base case: null node has depth 0.', 'Simple DFS recursion solves this in 3 lines.'],
    pattern_explanation: 'DFS recursion. Height = 1 + max(left, right). O(n).',
    solution: `function maxDepth(root) {\n  if (!root) return 0;\n  return 1 + Math.max(maxDepth(root.left), maxDepth(root.right));\n}`,
    testCases: [] },
  { id: 18, title: 'Validate BST', difficulty: 'Medium', pattern: 'DFS with Bounds', viz: 'bst',
    description: 'Given the root of a binary tree, determine if it is a valid binary search tree (left subtree values < node < right subtree values, recursively).',
    examples: [{ input: 'root = [2,1,3]', output: 'true', explanation: '1 < 2 < 3, valid BST.' }],
    hints: ['Checking just left < root < right is not enough — the entire left subtree must be less than root.', 'Pass min and max bounds as you recurse down.', 'Left child: max bound becomes parent value. Right child: min bound becomes parent value.'],
    pattern_explanation: 'DFS with propagated bounds. Common BST validation pattern.',
    solution: `function isValidBST(root, min=-Infinity, max=Infinity) {\n  if (!root) return true;\n  if (root.val <= min || root.val >= max) return false;\n  return isValidBST(root.left, min, root.val) && isValidBST(root.right, root.val, max);\n}`,
    testCases: [] },
];
export const heapProblems = [
  { id: 19, title: 'Kth Largest Element', difficulty: 'Medium', pattern: 'Min-Heap', viz: 'heap',
    description: 'Given an integer array, return the kth largest element (not kth distinct).',
    examples: [{ input: 'nums = [3,2,1,5,6,4], k = 2', output: '5', explanation: '2nd largest is 5.' }],
    hints: ['Sorting works but O(n log n) — can you do better?', 'A min-heap of size K always holds the K largest elements seen so far.', 'Push each element. If heap size > K pop the minimum. After full scan heap top = Kth largest.'],
    pattern_explanation: 'Min-heap of size K. O(n log k) time.',
    solution: `// JavaScript lacks a built-in heap. Use a sorted approach or implement MinHeap.\nfunction findKthLargest(nums, k) {\n  nums.sort((a,b) => b - a);\n  return nums[k - 1];\n}`,
    testCases: [{ input: [[3,2,1,5,6,4], 2], expected: 5 }, { input: [[3,2,3,1,2,4,5,5,6], 4], expected: 4 }] },
  { id: 20, title: 'Top K Frequent Elements', difficulty: 'Medium', pattern: 'Heap + HashMap', viz: 'heap',
    description: 'Given an integer array and k, return the k most frequent elements in any order.',
    examples: [{ input: 'nums = [1,1,1,2,2,3], k = 2', output: '[1,2]', explanation: '1 appears 3 times, 2 appears 2 times.' }],
    hints: ['First count frequencies using a hash map.', 'Then find the K elements with highest frequency.', 'Bucket sort trick: create array indexed by frequency (max = n). Scan right to left to collect K elements.'],
    pattern_explanation: 'Bucket sort by frequency. O(n) time using array of size n.',
    solution: `function topKFrequent(nums, k) {\n  const freq = new Map(), buckets = Array.from({length: nums.length+1}, ()=>[]);\n  for (const n of nums) freq.set(n, (freq.get(n)||0)+1);\n  for (const [n,f] of freq) buckets[f].push(n);\n  const res = [];\n  for (let i = buckets.length-1; i >= 0 && res.length < k; i--) res.push(...buckets[i]);\n  return res.slice(0,k);\n}`,
    testCases: [{ input: [[1,1,1,2,2,3], 2], expected: [1,2] }] },
];
export const graphProblems = [
  { id: 21, title: 'Number of Islands', difficulty: 'Medium', pattern: 'DFS Grid', viz: 'graph',
    description: 'Given a 2D grid of "1" (land) and "0" (water), count the number of islands. An island is surrounded by water and formed by connecting adjacent land cells horizontally or vertically.',
    examples: [{ input: 'grid = [["1","1","0"],["0","1","0"],["0","0","1"]]', output: '2', explanation: 'Two separate island groups.' }],
    hints: ['Scan every cell. When you find unvisited land, you found a new island.', 'DFS/BFS from that cell to mark all connected land cells as visited.', 'Count how many times you start a fresh DFS.'],
    pattern_explanation: 'Grid DFS/BFS. Mark visited by setting cell to "0". O(m×n).',
    solution: `function numIslands(grid) {\n  let count = 0;\n  const dfs = (r,c) => {\n    if (r<0||r>=grid.length||c<0||c>=grid[0].length||grid[r][c]==='0') return;\n    grid[r][c]='0';\n    dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1);\n  };\n  for (let r=0;r<grid.length;r++) for (let c=0;c<grid[0].length;c++) if (grid[r][c]==='1') { dfs(r,c); count++; }\n  return count;\n}`,
    testCases: [] },
  { id: 22, title: 'Course Schedule', difficulty: 'Medium', pattern: 'Cycle Detection', viz: 'graph',
    description: 'There are n courses (0 to n-1). Given prerequisites [a,b] meaning b must be taken before a, determine if it is possible to finish all courses.',
    examples: [{ input: 'n=2, prerequisites=[[1,0]]', output: 'true', explanation: 'Take course 0 then 1.' }, { input: 'n=2, prerequisites=[[1,0],[0,1]]', output: 'false', explanation: 'Circular dependency.' }],
    hints: ['This is a cycle detection problem on a directed graph.', 'Build an adjacency list. DFS each unvisited node.', 'Track 3 states: 0=unvisited, 1=visiting (in current DFS path), 2=done. If you reach a node with state 1 → cycle.'],
    pattern_explanation: 'DFS cycle detection with 3-state coloring. Core graph pattern.',
    solution: `function canFinish(n, prereqs) {\n  const adj = Array.from({length:n},()=>[]);\n  for (const [a,b] of prereqs) adj[b].push(a);\n  const state = new Array(n).fill(0);\n  const dfs = v => {\n    if (state[v]===1) return false;\n    if (state[v]===2) return true;\n    state[v]=1;\n    for (const u of adj[v]) if (!dfs(u)) return false;\n    state[v]=2; return true;\n  };\n  for (let i=0;i<n;i++) if (!dfs(i)) return false;\n  return true;\n}`,
    testCases: [{ input: [2,[[1,0]]], expected: true }, { input: [2,[[1,0],[0,1]]], expected: false }] },
];
export const sortingProblems = [
  { id: 23, title: 'Sort Colors', difficulty: 'Medium', pattern: 'Dutch National Flag', viz: 'bubble',
    description: 'Given an array with values 0, 1, 2 representing red, white and blue, sort in-place so all 0s come first, then 1s, then 2s — without using a sort function.',
    examples: [{ input: 'nums = [2,0,2,1,1,0]', output: '[0,0,1,1,2,2]', explanation: 'In-place partition.' }],
    hints: ['Counting sort works — count 0s, 1s, 2s then fill. But can you do one pass?', "Dutch National Flag algorithm uses 3 pointers: lo, mid, hi.", 'If nums[mid]=0 swap with lo, advance both. If 2 swap with hi, retreat hi. If 1 just advance mid.'],
    pattern_explanation: "Dutch National Flag: 3-pointer one-pass O(n) in-place sort.",
    solution: `function sortColors(nums) {\n  let lo=0, mid=0, hi=nums.length-1;\n  while (mid<=hi) {\n    if (nums[mid]===0) { [nums[lo],nums[mid]]=[nums[mid],nums[lo]]; lo++; mid++; }\n    else if (nums[mid]===2) { [nums[mid],nums[hi]]=[nums[hi],nums[mid]]; hi--; }\n    else mid++;\n  }\n}`,
    testCases: [{ input: [[2,0,2,1,1,0]], expected: [0,0,1,1,2,2] }] },
];
