export const linkedlistProblems = [
  {
    id: 9,
    title: 'Reverse Linked List',
    difficulty: 'Easy',
    pattern: 'Reversal',
    viz: 'linkedlist',
    timeO: 'O(n)',
    spaceO: 'O(1)',
    description: 'Given the head of a singly linked list, reverse the list and return the new head.',
    examples: [
      { input: 'head = [1,2,3,4,5]', output: '[5,4,3,2,1]', explanation: 'Each node pointer is reversed so the list order flips.' },
      { input: 'head = [1,2]', output: '[2,1]', explanation: 'The second node becomes the new head.' },
    ],
    hints: [
      'You need to reverse each next pointer one node at a time.',
      'Track three things: the previous node, the current node, and the next node before you overwrite links.',
      'After changing current.next, advance prev and current forward.',
    ],
    pattern_explanation: 'The standard three-pointer linked list reversal runs in linear time and constant extra space.',
    solution: 'function reverseList(head) {\\n  let prev = null;\\n  let curr = head;\\n  while (curr) {\\n    const next = curr.next;\\n    curr.next = prev;\\n    prev = curr;\\n    curr = next;\\n  }\\n  return prev;\\n}',
    testCases: [
      { input: [[1,2,3,4,5]], expected: [5,4,3,2,1] },
      { input: [[1,2]], expected: [2,1] },
      { input: [[]], expected: [] },
    ],
  },
  {
    id: 10,
    title: 'Linked List Cycle',
    difficulty: 'Easy',
    pattern: 'Fast and Slow Pointer',
    viz: 'linkedlist',
    timeO: 'O(n)',
    spaceO: 'O(1)',
    description: 'Given the head of a linked list, determine whether the list contains a cycle.',
    examples: [
      { input: 'head = [3,2,0,-4], tail connects to index 1', output: 'true', explanation: 'The list loops back to a previous node.' },
      { input: 'head = [1], no cycle', output: 'false', explanation: 'Traversal reaches null, so the list ends normally.' },
    ],
    hints: [
      'A set-based solution works, but there is an O(1) space approach.',
      'Move one pointer one step at a time and another pointer two steps at a time.',
      'If there is a cycle, the faster pointer will eventually catch the slower one.',
    ],
    pattern_explanation: 'Floyd’s tortoise and hare algorithm detects cycles using two pointers moving at different speeds.',
    solution: 'function hasCycle(head) {\\n  let slow = head;\\n  let fast = head;\\n  while (fast && fast.next) {\\n    slow = slow.next;\\n    fast = fast.next.next;\\n    if (slow === fast) return true;\\n  }\\n  return false;\\n}',
    testCases: [
      { input: ['cycle-present'], expected: true },
      { input: ['no-cycle'], expected: false },
    ],
  },
  {
    id: 11,
    title: 'Merge Two Sorted Lists',
    difficulty: 'Easy',
    pattern: 'Two Pointer',
    viz: 'linkedlist',
    timeO: 'O(n + m)',
    spaceO: 'O(1)',
    description: 'Merge two sorted linked lists and return the head of the merged sorted list.',
    examples: [
      { input: 'l1 = [1,2,4], l2 = [1,3,4]', output: '[1,1,2,3,4,4]', explanation: 'Pick the smaller current node each step and stitch the result together.' },
    ],
    hints: [
      'A dummy head node helps avoid special-casing the first insertion.',
      'Compare the heads of the two lists and attach the smaller one to the result.',
      'When one list is exhausted, attach the remainder of the other list directly.',
    ],
    pattern_explanation: 'This is the classic two-pointer merge process adapted from merge sort to linked lists.',
    solution: 'function mergeTwoLists(l1, l2) {\\n  const dummy = { next: null };\\n  let tail = dummy;\\n  while (l1 && l2) {\\n    if (l1.val <= l2.val) {\\n      tail.next = l1;\\n      l1 = l1.next;\\n    } else {\\n      tail.next = l2;\\n      l2 = l2.next;\\n    }\\n    tail = tail.next;\\n  }\\n  tail.next = l1 || l2;\\n  return dummy.next;\\n}',
    testCases: [
      { input: [[[1,2,4], [1,3,4]]], expected: [1,1,2,3,4,4] },
      { input: [[[], []]], expected: [] },
      { input: [[[], [0]]], expected: [0] },
    ],
  },
  {
    id: 12,
    title: 'Remove Nth Node From End',
    difficulty: 'Medium',
    pattern: 'Two Pointer',
    viz: 'linkedlist',
    timeO: 'O(n)',
    spaceO: 'O(1)',
    description: 'Given the head of a linked list, remove the nth node from the end and return the head.',
    examples: [
      { input: 'head = [1,2,3,4,5], n = 2', output: '[1,2,3,5]', explanation: 'The node with value 4 is the second node from the end.' },
      { input: 'head = [1], n = 1', output: '[]', explanation: 'Removing the only node leaves an empty list.' },
    ],
    hints: [
      'A dummy node helps handle removing the head cleanly.',
      'Move a fast pointer n + 1 steps ahead of a slow pointer.',
      'When the fast pointer reaches the end, the slow pointer is just before the node to remove.',
    ],
    pattern_explanation: 'The fixed-gap two-pointer technique lets you remove the target node in one pass.',
    solution: 'function removeNthFromEnd(head, n) {\\n  const dummy = { next: head };\\n  let fast = dummy;\\n  let slow = dummy;\\n  for (let i = 0; i <= n; i++) fast = fast.next;\\n  while (fast) {\\n    fast = fast.next;\\n    slow = slow.next;\\n  }\\n  slow.next = slow.next.next;\\n  return dummy.next;\\n}',
    testCases: [
      { input: [[[1,2,3,4,5], 2]], expected: [1,2,3,5] },
      { input: [[[1], 1]], expected: [] },
      { input: [[[1,2], 1]], expected: [1] },
    ],
  },
];
