export const stackProblems = [
  {
    id: 6,
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    pattern: 'Stack Matching',
    viz: 'stack',
    timeO: 'O(n)',
    spaceO: 'O(n)',
    description: 'Given a string containing only parentheses characters, determine if the brackets are valid. Every opening bracket must be closed by the same type in the correct order.',
    examples: [
      { input: 's = "()"', output: 'true', explanation: 'A single valid pair closes correctly.' },
      { input: 's = "()[]{}"', output: 'true', explanation: 'Each opening bracket is matched in the correct order.' },
      { input: 's = "(]"', output: 'false', explanation: 'The closing bracket does not match the latest opening bracket.' },
    ],
    hints: [
      'When you see an opening bracket, you need to remember it for later.',
      'The last bracket opened must be the first one closed, which is exactly how a stack works.',
      'Push openers onto the stack. On a closing bracket, the stack top must be the matching opener.',
    ],
    pattern_explanation: 'This is a direct stack application because bracket matching is a last-opened, first-closed process.',
    solution: 'function isValid(s) {\\n  const stack = [];\\n  const pairs = { ")": "(", "}": "{", "]": "[" };\\n  for (const ch of s) {\\n    if ("([{".includes(ch)) stack.push(ch);\\n    else if (stack.pop() !== pairs[ch]) return false;\\n  }\\n  return stack.length === 0;\\n}',
    testCases: [
      { input: ['()'], expected: true },
      { input: ['()[]{}'], expected: true },
      { input: ['(]'], expected: false },
      { input: ['([)]'], expected: false },
    ],
  },
  {
    id: 7,
    title: 'Min Stack',
    difficulty: 'Medium',
    pattern: 'Stack Design',
    viz: 'stack',
    timeO: 'O(1)',
    spaceO: 'O(n)',
    description: 'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.',
    examples: [
      {
        input: 'push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()',
        output: '-3, 0, -2',
        explanation: 'A second stack can track the minimum value seen at each depth.',
      },
    ],
    hints: [
      'The minimum can change after every push and pop, so one stack alone is not enough.',
      'Use a second stack where each position stores the minimum value up to that depth.',
      'When pushing a value, also push the new minimum onto the min stack.',
    ],
    pattern_explanation: 'Use two synchronized stacks: one for values and one for running minimums.',
    solution: 'class MinStack {\\n  constructor() {\\n    this.stack = [];\\n    this.minStack = [];\\n  }\\n  push(val) {\\n    this.stack.push(val);\\n    const min = this.minStack.length ? Math.min(val, this.minStack[this.minStack.length - 1]) : val;\\n    this.minStack.push(min);\\n  }\\n  pop() {\\n    this.stack.pop();\\n    this.minStack.pop();\\n  }\\n  top() {\\n    return this.stack[this.stack.length - 1];\\n  }\\n  getMin() {\\n    return this.minStack[this.minStack.length - 1];\\n  }\\n}',
    testCases: [
      { input: [['push', -2], ['push', 0], ['push', -3], ['getMin'], ['pop'], ['top'], ['getMin']], expected: [-3, 0, -2] },
    ],
  },
  {
    id: 8,
    title: 'Daily Temperatures',
    difficulty: 'Medium',
    pattern: 'Monotonic Stack',
    viz: 'stack',
    timeO: 'O(n)',
    spaceO: 'O(n)',
    description: 'Given an array of daily temperatures, return an array where result[i] is the number of days until a warmer temperature. If there is no future warmer day, return 0.',
    examples: [
      {
        input: 'temps = [73,74,75,71,69,72,76,73]',
        output: '[1,1,4,2,1,1,0,0]',
        explanation: 'For each day, track when a warmer future day first appears.',
      },
    ],
    hints: [
      'For each index, you want the next index to the right with a larger value.',
      'A monotonic decreasing stack of indices helps keep unresolved colder days.',
      'When the current temperature is warmer than the top index on the stack, resolve that earlier day.',
    ],
    pattern_explanation: 'A monotonic stack lets each index be pushed and popped at most once, giving O(n) total time.',
    solution: 'function dailyTemperatures(temperatures) {\\n  const result = new Array(temperatures.length).fill(0);\\n  const stack = [];\\n  for (let i = 0; i < temperatures.length; i++) {\\n    while (stack.length && temperatures[i] > temperatures[stack[stack.length - 1]]) {\\n      const prev = stack.pop();\\n      result[prev] = i - prev;\\n    }\\n    stack.push(i);\\n  }\\n  return result;\\n}',
    testCases: [
      { input: [[73,74,75,71,69,72,76,73]], expected: [1,1,4,2,1,1,0,0] },
      { input: [[30,40,50,60]], expected: [1,1,1,0] },
      { input: [[30,60,90]], expected: [1,1,0] },
    ],
  },
];
