export const bsearchProblems = [
  {
    id: 13,
    title: 'Binary Search',
    difficulty: 'Easy',
    pattern: 'Binary Search',
    viz: 'bsearch',
    timeO: 'O(log n)',
    spaceO: 'O(1)',
    description: 'Given a sorted array of integers and a target, return the index of the target. If not found return -1. Must run in O(log n).',
    examples: [
      { input: 'nums = [-1,0,3,5,9,12], target = 9', output: '4', explanation: '9 is at index 4.' },
      { input: 'nums = [-1,0,3,5,9,12], target = 2', output: '-1', explanation: '2 is not in the array.' },
    ],
    hints: [
      'The array is sorted — use that fact to eliminate half the search space each step.',
      'Set lo = 0 and hi = n - 1. Compute mid = Math.floor((lo + hi) / 2) each iteration.',
      'If target < nums[mid], search left half. If target > nums[mid], search right half. Otherwise return mid.',
    ],
    pattern_explanation: 'Classic binary search template. O(log n) time and O(1) space. This pattern is the base for many search-on-answer problems.',
    solution: 'function search(nums, target) {\\n  let lo = 0, hi = nums.length - 1;\\n  while (lo <= hi) {\\n    const mid = (lo + hi) >> 1;\\n    if (nums[mid] === target) return mid;\\n    if (nums[mid] < target) lo = mid + 1;\\n    else hi = mid - 1;\\n  }\\n  return -1;\\n}',
    testCases: [
      { input: [[-1,0,3,5,9,12], 9], expected: 4 },
      { input: [[-1,0,3,5,9,12], 2], expected: -1 },
      { input: [[5], 5], expected: 0 },
    ],
  },
  {
    id: 14,
    title: 'Find Minimum in Rotated Sorted Array',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    viz: 'bsearch',
    timeO: 'O(log n)',
    spaceO: 'O(1)',
    description: 'A sorted array was rotated at some pivot. Find the minimum element in O(log n).',
    examples: [
      { input: 'nums = [3,4,5,1,2]', output: '1', explanation: 'The smallest value appears at the rotation point.' },
      { input: 'nums = [4,5,6,7,0,1,2]', output: '0', explanation: 'The rotated half contains the minimum.' },
    ],
    hints: [
      'The minimum lies at the point where sorted order breaks.',
      'Compare nums[mid] with nums[hi] to decide which half contains the minimum.',
      'If nums[mid] > nums[hi], the minimum is in the right half. Otherwise it is in the left half including mid.',
    ],
    pattern_explanation: 'Modified binary search using the sorted property of one side of the array. O(log n) time, O(1) space.',
    solution: 'function findMin(nums) {\\n  let lo = 0, hi = nums.length - 1;\\n  while (lo < hi) {\\n    const mid = (lo + hi) >> 1;\\n    if (nums[mid] > nums[hi]) lo = mid + 1;\\n    else hi = mid;\\n  }\\n  return nums[lo];\\n}',
    testCases: [
      { input: [[3,4,5,1,2]], expected: 1 },
      { input: [[4,5,6,7,0,1,2]], expected: 0 },
      { input: [[11,13,15,17]], expected: 11 },
    ],
  },
  {
    id: 15,
    title: 'Koko Eating Bananas',
    difficulty: 'Medium',
    pattern: 'Search on Answer',
    viz: 'bsearch',
    timeO: 'O(n log m)',
    spaceO: 'O(1)',
    description: 'Koko has n piles of bananas and h hours. She eats at speed k bananas per hour, one pile per hour. Find the minimum integer k needed to finish all piles within h hours.',
    examples: [
      { input: 'piles = [3,6,7,11], h = 8', output: '4', explanation: 'At speed 4, total hours needed is exactly 8.' },
      { input: 'piles = [30,11,23,4,20], h = 5', output: '30', explanation: 'She must eat at least 30 bananas per hour to finish in 5 hours.' },
    ],
    hints: [
      'The answer is not an index in the array — it is a value in a search range from 1 to max(piles).',
      'For a chosen speed k, compute total hours as the sum of Math.ceil(pile / k).',
      'If a speed works, try a smaller one. If it does not work, search higher.',
    ],
    pattern_explanation: 'Binary search on the answer space. The feasibility check is monotonic, which makes binary search valid.',
    solution: 'function minEatingSpeed(piles, h) {\\n  let lo = 1, hi = Math.max(...piles);\\n  while (lo < hi) {\\n    const mid = (lo + hi) >> 1;\\n    const hours = piles.reduce((sum, pile) => sum + Math.ceil(pile / mid), 0);\\n    if (hours <= h) hi = mid;\\n    else lo = mid + 1;\\n  }\\n  return lo;\\n}',
    testCases: [
      { input: [[3,6,7,11], 8], expected: 4 },
      { input: [[30,11,23,4,20], 5], expected: 30 },
      { input: [[30,11,23,4,20], 6], expected: 23 },
    ],
  },
];
